### ISSUE TITLE
Spinda Problem

### ISSUE THREAD

**Issue by PQRachel** [CajunAvenger/cajunavenger.github.io#28]
When you download the final image the spinda's head is pure white instead of the normal tan color like the rest of the spinda.
Here's my download image as an example:
![Fav Pokémon 2023 Mar](https://user-images.githubusercontent.com/88564179/223974977-3a28a750-7ff8-4723-ad0b-3f80e89d33cf.png)

**Comment by CajunAvenger** [comment]
Looks like this can happen because the because the site "forgets" you've picked Spinda due to it being a weirder box. You can fix this currently by clicking Write Code, then in the first line where it says `NestBall,,VIVILLON_19` change that to `NestBall,SPINDA,VIVILLON_19`, then click Import Code. I'll poke at fixing it altogether later tonight.
