### ISSUE TITLE
Gimmick Form Inconsistency

### ISSUE THREAD

**Issue by CoolBeansiest** [CajunAvenger/cajunavenger.github.io#34]
Made a github acc 20min ago just to ask why Castform's weather forms, Keldeo's resolute form, and Paradox forms are not classified as gimmick forms, while Toedscruel, Wugtrio, and Primal Groudon are? You could argue that they were introduced in different generations, but that doesn't make them a gimmick?? Just feels a little inconsistent. If the Paradox Pokemon are not gimmicks, then neither should Wugtrio or Toedscruel. Same with Keldeo, Kyrurem, Castform, Aegislash, etc
Similarly, why do Mega and GMax forms count towards Gen 1-5 gimmicks, but not Alolan and Galarian forms?

**Comment by CajunAvenger** [comment]
Gimmick form refers to the mechanical gimmick of a generation, such as gen 6 Megas, gen 7 regional forms, gen 8 gigantamax, and gen 9 convergent forms. Paradox are certainly borderline, but they have their own box to themself and they are completely different Pokedex numbers, which gets things like Clodsire removed.

Keldeo, Kyurem, Castform, and Aegislash don't fit in there at all, those are just forms. On the flip side, Primal Groudon is effectively Mega Groudon so it gets in with the Megas.

Megas were put in the early gens because otherwise Gens 1-5 get about three gimmick forms between them. Regional forms were not as that would cause Gen 1 gets about 70 forms and the rest of the gens fight for scraps.
