### ISSUE TITLE
Spinda painter

### ISSUE THREAD

**Issue by foreverFlummoxed** [CajunAvenger/cajunavenger.github.io#90]
Hello, this a minor thing that most people probably won't care about but i happened to notice anyway: the way the "16 values" of the vertical/horizontal position of Spinda's spots works is that it uses 1 nibble (which in binary is a group of 4 bits which has 16 possible values that include 0, making them: 0-15) of the 32-bit integer to determine it's position, so the fact the painter can go up to 16 and include 0 as a value makes certain patterns with this painter... literally impossible, lol.

though i can give the info that the top-and-left-most positions for a single spot correspond to a 00 hex-value for a byte (two nibbles, vertical & horizontal values put together) in Spinda's personality value with the left digit corresponding to vertical movement and the right digit to horizontal movement.

(3d Spinda models use the encryption constant for spots, so personality value is the accurate term for the sprite)
"hex-value" is a way of reading binary that displays nibbles as a single digit, so "1001" becomes 9. 10-15 use the letters A-F to represent those values in a single digit, 1010 becomes A. (not trying to act smart, just realized i didn't have room above to explain to anyone that doesn't know about binary and hexadecimal notation without making this more cluttered)

**Comment by CajunAvenger** [comment]
yeaa its a bit of a simplification. the old spinda painter (...that seems to have fallen off the internet) only had the gen 3 sprite rather than then newer and bigger one we have here, so I couldn't make a perfectly perfect one. Even at 0-15 range there's probably technically impossible Spindas so have the 0-16 to make the math easier and adding the fully bald Spinda is fun.
